"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userController_1 = require("../../controllers/userController/userController");
const verifyUser_1 = require("../../utils/verifyUser");
const router = express_1.default.Router();
router.post("/signup", userController_1.signup);
router.post("/login", userController_1.userLogin);
router.post("/contact", userController_1.contactPage);
router.post("/otp", userController_1.otpVerification);
router.post("/otp/resend", userController_1.resendOTP);
router.post("/mail4otp", userController_1.mail4otp);
router.get("/getAllPost", verifyUser_1.verifyUser, userController_1.getAllPost);
router.post("/update-like", verifyUser_1.verifyUser, userController_1.updateLike);
router.post("/report", verifyUser_1.verifyUser, userController_1.handleReport);
router.post("/search", verifyUser_1.verifyUser, userController_1.searchPainters);
router.get("/profile/:id", verifyUser_1.verifyUser, userController_1.userProfile);
router.patch("/add-address", verifyUser_1.verifyUser, userController_1.addAddress);
router.get("/painter/profile/:id", verifyUser_1.verifyUser, userController_1.ClientPainterProfile);
router.post("/followPainter", verifyUser_1.verifyUser, userController_1.followPainter);
router.get("/painter/profile/followerList/:id", verifyUser_1.verifyUser, userController_1.followerList);
router.post("/painter/profile/indMsg", verifyUser_1.verifyUser, userController_1.painterIndMsg);
router.post("/post/comments", verifyUser_1.verifyUser, userController_1.createComment);
router.patch("/profile/change-password", verifyUser_1.verifyUser, userController_1.changePassword);
router.put("/profile/updateUserProfile", verifyUser_1.verifyUser, userController_1.updateUserProfile);
router.post("/painter/slot-booking", verifyUser_1.verifyUser, userController_1.bookedSlot);
router.post("/hashtags", verifyUser_1.verifyUser, userController_1.getHashtags);
exports.default = router;
//# sourceMappingURL=userRoute.js.map